-- Añadir nuevas columnas a la tabla site_settings
ALTER TABLE public.site_settings 
ADD COLUMN IF NOT EXISTS home_title_en TEXT,
ADD COLUMN IF NOT EXISTS home_title_es TEXT,
ADD COLUMN IF NOT EXISTS home_pretitle_en TEXT,
ADD COLUMN IF NOT EXISTS home_pretitle_es TEXT,
ADD COLUMN IF NOT EXISTS home_subtitle_en TEXT,
ADD COLUMN IF NOT EXISTS home_subtitle_es TEXT,
ADD COLUMN IF NOT EXISTS logo_url TEXT,
ADD COLUMN IF NOT EXISTS team_subtitle_en TEXT,
ADD COLUMN IF NOT EXISTS team_subtitle_es TEXT,
ADD COLUMN IF NOT EXISTS contact_title_en TEXT,
ADD COLUMN IF NOT EXISTS contact_title_es TEXT,
ADD COLUMN IF NOT EXISTS contact_subtitle_en TEXT,
ADD COLUMN IF NOT EXISTS contact_subtitle_es TEXT,
ADD COLUMN IF NOT EXISTS contact_description_en TEXT,
ADD COLUMN IF NOT EXISTS contact_description_es TEXT,
ADD COLUMN IF NOT EXISTS footer_description_en TEXT,
ADD COLUMN IF NOT EXISTS footer_description_es TEXT,
ADD COLUMN IF NOT EXISTS filter_all_en TEXT,
ADD COLUMN IF NOT EXISTS filter_all_es TEXT,
ADD COLUMN IF NOT EXISTS filter_build_en TEXT,
ADD COLUMN IF NOT EXISTS filter_build_es TEXT,
ADD COLUMN IF NOT EXISTS filter_complete_en TEXT,
ADD COLUMN IF NOT EXISTS filter_complete_es TEXT,
ADD COLUMN IF NOT EXISTS social_links JSONB;
