-- Update script for site_settings table to support the new features
-- Run this in your Supabase SQL Editor

ALTER TABLE public.site_settings 
ADD COLUMN IF NOT EXISTS logo_alt TEXT,
ADD COLUMN IF NOT EXISTS team_subtitle_en TEXT,
ADD COLUMN IF NOT EXISTS team_subtitle_es TEXT,
ADD COLUMN IF NOT EXISTS home_title_en TEXT,
ADD COLUMN IF NOT EXISTS home_title_es TEXT,
ADD COLUMN IF NOT EXISTS home_pretitle_en TEXT,
ADD COLUMN IF NOT EXISTS home_pretitle_es TEXT,
ADD COLUMN IF NOT EXISTS home_subtitle_en TEXT,
ADD COLUMN IF NOT EXISTS home_subtitle_es TEXT,
ADD COLUMN IF NOT EXISTS home_bg_image TEXT,
ADD COLUMN IF NOT EXISTS highlights_title_en TEXT,
ADD COLUMN IF NOT EXISTS highlights_title_es TEXT,
ADD COLUMN IF NOT EXISTS services_title_en TEXT,
ADD COLUMN IF NOT EXISTS services_title_es TEXT,
ADD COLUMN IF NOT EXISTS services_description_en TEXT,
ADD COLUMN IF NOT EXISTS services_description_es TEXT,
ADD COLUMN IF NOT EXISTS services_btn1_en TEXT,
ADD COLUMN IF NOT EXISTS services_btn1_es TEXT,
ADD COLUMN IF NOT EXISTS services_btn2_en TEXT,
ADD COLUMN IF NOT EXISTS services_btn2_es TEXT,
ADD COLUMN IF NOT EXISTS services_stat1_value TEXT,
ADD COLUMN IF NOT EXISTS services_stat1_label_en TEXT,
ADD COLUMN IF NOT EXISTS services_stat1_label_es TEXT,
ADD COLUMN IF NOT EXISTS services_stat2_value TEXT,
ADD COLUMN IF NOT EXISTS services_stat2_label_en TEXT,
ADD COLUMN IF NOT EXISTS services_stat2_label_es TEXT,
ADD COLUMN IF NOT EXISTS services_stat3_value TEXT,
ADD COLUMN IF NOT EXISTS services_stat3_label_en TEXT,
ADD COLUMN IF NOT EXISTS services_stat3_label_es TEXT,
ADD COLUMN IF NOT EXISTS services_stat4_value TEXT,
ADD COLUMN IF NOT EXISTS services_stat4_label_en TEXT,
ADD COLUMN IF NOT EXISTS services_stat4_label_es TEXT,
ADD COLUMN IF NOT EXISTS services_media_type TEXT,
ADD COLUMN IF NOT EXISTS services_video_url TEXT,
ADD COLUMN IF NOT EXISTS services_image_1 TEXT,
ADD COLUMN IF NOT EXISTS services_image_2 TEXT,
ADD COLUMN IF NOT EXISTS services_image_3 TEXT,
ADD COLUMN IF NOT EXISTS services_image_4 TEXT;

